trigger:
  - main

variables:
  imageRepository: fridayshop-app
  containerRegistry: myacrname.azurecr.io
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        steps:
          - task: Docker@2
            displayName: Build and push Docker image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: |
                $(containerRegistry)
              tags: |
                $(tag)

  - stage: Deploy
    jobs:
      - deployment: DeployToAKS
        environment: 'AKS.prod'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@1
                  inputs:
                    action: deploy
                    kubernetesServiceConnection: 'AKSConnection'
                    namespace: 'default'
                    manifests: |
                      $(System.DefaultWorkingDirectory)/deployment.yaml
                    containers: |
                      $(containerRegistry)/$(imageRepository):$(tag)
